### ISSUE TITLE
Binario-decimal-binario

### ISSUE THREAD

**Issue by ioliasa** [josevazquez99/Programaci-nPonermealDia#1]
Realiza un método que reciba una cadena que represente a un número decimal y devuelva una cadena con la representación binaria del número.

Tu haces otro método que recibe un integer y devuelve otro integer, la idea es que trabajes con cadenas. Hazlo como se pide

**Comment by josevazquez99** [comment]
Buenos días , revisalo cuando usted pueda Inma.

**Comment by ioliasa** [comment]
Perfect!!!
