### ISSUE TITLE
Ejercicio Rectangulo

### ISSUE THREAD

**Issue by josevazquez99** [josevazquez99/Programaci-nPonermealDia#2]
Buenos días Inma revisame cuando puedas el de Rectángulo, voy a seguir haciendo ejercicios de ese boletín.

**Comment by ioliasa** [comment]
Si te dice " cada uno con un valor predeterminado igual a 1." Te está diciendo que debes crear un constructor que cree un rectángulo con esos valores, es decir, en este caso tienes que tener el constructor que tu has puesto y otro constuctor que no reciba ningún argumento.
Por lo demás, ok

**Comment by ioliasa** [comment]
José, la función del constructor es poner los atributos con su valor, realmente funcionaría como lo tienes, pero lo suyo es que el constructor sea algo así como esto, así te acostumbras a darle el valor en los constructores
	
	public Rectangulo(){
            longitud = 1;
           ancho = 1;
	
	}
