### ISSUE TITLE
Máquina Cafe

### ISSUE THREAD

**Issue by josevazquez99** [josevazquez99/Programaci-nPonermealDia#5]
Buenos días Inma, cuando usted pueda revísame el ejercicio de máquina de café.

**Comment by ioliasa** [comment]
El precio también es común para todas las máquinas, así que debería ser también estático.

Llenar depósitivo te decía que se llenaban hasta arriba, así que no recibe nada. Y luego los set de los depósitos no es posible, porque te dice que se llenan todos a la vez. El único que creo que tiene sentido es el setMonedero, pero creo recordar que también pedía vaciar el monedero.

**Comment by ioliasa** [comment]
Cuando tengas corregido lo anterior, cambia que en vez de devolver mensajes lance exceptions.

**Comment by josevazquez99** [comment]
Buenas tardes Inma, revisalo cuando usted pueda.

**Comment by ioliasa** [comment]
El lanzarla si está bien, pero el recogerla en el principal no la recoges. En el main tienes que recogerla con try catch y mostrar al usuario el mensaje de error adecuado.

**Comment by josevazquez99** [comment]
Buenos días Inma, creo que ya estaría echo en el principal con el try y el catch , revísalo cuando usted pueda.

**Comment by ioliasa** [comment]
Perfecto
