### ISSUE TITLE
Avion

### ISSUE THREAD

**Issue by josevazquez99** [josevazquez99/Programaci-nPonermealDia#7]
Buenos días Inma,revisa cuando puedas el ejercicio de avion

**Comment by ioliasa** [comment]
En el get no tiene sentido la exception, es para informar que algo va mal

**Comment by ioliasa** [comment]
Repasa el menu principial, debe haber dos menus

**Comment by josevazquez99** [comment]
Creo que ya está corregido

**Comment by ioliasa** [comment]
No debes duplicar el código, lo que tienes que hacer es un menú para decir si lo creas de una forma u otra, y luego otro menú con el objeto creado. Si quieres recuérdamelo el jueves y te lo explico en clase

**Comment by josevazquez99** [comment]
Buenas,¿,a eso se refiere Inma?

**Comment by ioliasa** [comment]
Exacto
